# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e77d332e18e79fe2a24f526201f50a4bf2f0e41a4c12db38dcb93d3b8ffb3f32a95a4351c74ecd8cc632582e770fc94bdbe3b302edf4f24949c5860b09d0c1ae

test:
  secret_key_base: 1d6c7fa03f37627b3a6471acc4133ee4d4fc964b5d56b6907725c669bf3d0d1f3d39eb73973e742de377f0a0af2239237f3366e22cb106df34e5ef635e35b97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
